services:
  sales-service:
    container_name: sales-service
    build:
      context: ./packages/sales-service
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgrespw
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: